[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor --log-format=defmt --no-stub"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  # "-C", "force-frame-pointers",

  # --- ADD following new flag ---
  "-C", "link-arg=-Tdefmt.x",
  ]

[build]
target = "riscv32imc-unknown-none-elf"

# [unstable]
# build-std = ["core"]

[env]
ESP_LOG="INFO"

[alias]
test_pc = "test --target=x86_64-unknown-linux-gnu"
